# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Lixingcong
subtitle: 我的博客
description: 推特宅男一枚，失业中 
keywords:
author: Lixingcong
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: lixingcong.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年M月D日
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

archive_generator:
  yearly: true
  monthly: true
  per_page: 0

category_generator:
  per_page: 0

tag_generator:
  per_page: 0

marked:
  smartypants: false

theme_config:
  github_banner:
    enable: false
    permalink: https://github.com/yourname
    title: Follow me on GitHub

  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive

  scheme: Gemini

  sidebar:
    display: always
    onmobile: false

  scroll_to_more: false

  highlight_theme: night eighties

  math:
    per_page: false
    mathjax:
      enable: true
      mhchem: false
    katex:
      enable: false
      copy_tex: false


  google_analytics:
    tracking_id: UA-66672466-1
    only_pageview: true

  social:
    Twitter: https://twitter.com/lixingcong || twitter
    Github: https://github.com/lixingcong || github
    搬瓦工: https://bandwagonhost.com/aff.php?aff=17660 || shopping-cart
    Vultr: https://www.vultr.com/?ref=7141078 || shopping-cart
  
  motion:
    enable: false
  
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: false
      another_day: true
    categories: true
  
  rss: false
  vendors:
    _internal: lib
    mathjax: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

  post_edit:
    enable: true
    url: https://github.com/lixingcong/my-hexo-blog2/blob/master/source/ # Link for view source
