name: build

on:
  push:
    push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Hexo
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Retrieve ssh private key from secret
        env:
          SSH_DEPLOY_PRIVATE_KEY: ${{secrets.SSH_DEPLOY_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: |
          npm install -g hexo-cli
          npm install hexo-util js-yaml --save

      - name: Init an empty hexo folder
        run: |
          hexo init hexo-empty-dir
          cd hexo-empty-dir
          npm install
          npm install theme-next/hexo-next-utteranc
          function linkFileHere { [[ -f $1 || -d $1 ]] && mv $1 $1.bak; ln -s ../$1 ./$1; }
          linkFileHere source
          linkFileHere themes
          linkFileHere deploy.sh
          linkFileHere _config.yml
          linkFileHere _config.next.yml

      - name: Generate and deploy
        run: |
          git config --global user.name  github-action
          git config --global user.email github-action@github.com
          hexo generate && bash deploy.sh
